spring:
  profiles:
    active: ${profileActive:dev}

logging:
  charset:
    console: UTF-8
    file: UTF-8
  file:
    name: log/${profileActive:dev}.log
  level:
    ml.sun: debug
  threshold:
    console: info
    file: debug
